### ISSUE TITLE
Typo in convertAndRead() example

### ISSUE THREAD

**Issue by fxframes** [stevemarple/MCP342x#14]
// 0x68 is the default address for all MCP342x devices
uint8_t address = 0x6E;

0x6E returns an error.
0x68 works normally.

**Comment by stevemarple** [comment]
That is not a typo. The correct address depends on the hardware (MCP3422, MCP3423, MCP3424, MCP3426, MCP3427, or MCP3428) and how any address selection lines are wired. On my board, for this example, 0x6E is correct. The address selection is documented in the project's [README](https://github.com/stevemarple/MCP342x/tree/master?tab=readme-ov-file#supported-devices).
