### ISSUE TITLE
Very nice job! I'm wondering if it's possible to use this lib for ATtin85, is it possible?

### ISSUE THREAD

**Issue by tom-4** [stevemarple/MCP342x#2]

**Comment by stevemarple** [comment]
I see no reason why not, unless the memory required exceeds that available in the ATtiny. Have a go with the demo code, does it compile and fit within the memory constraints?

**Comment by tom-4** [comment]
Thank you for you reply! I tried, but it didn't work. It's not a memory issue, it's about wiring (wire.h lib) I guess. As you know, the Attiny's need another wire lib (such tinywire.h) and because I'm not a programmer I couldn't fix it. If you have time and can fix this lib to work with Attiny85, it would be AWSOMEEEE!!!!

**Comment by vicatcu** [comment]
ATtiny85 doesn't have I2C hardware support iirc

**Comment by tom-4** [comment]
WHAT! The Attiny85 has I2C.  Pin5 for SDA and pin7 for SCL

**Comment by vicatcu** [comment]
So it does... my bad :)
