### ISSUE TITLE
list of functions

### ISSUE THREAD

**Issue by Fluxanode** [stevemarple/MCP342x#9]
I this lib supported anymore?  

It would be really cool if there was a list of the functions and their usage.

**Comment by Fluxanode** [comment]
is wire.h your 2wire lib or where is this library downloaded?

**Comment by stevemarple** [comment]
The library is [released under the GNU Lesser General Public License v2.1](https://github.com/stevemarple/MCP342x/blob/master/license.txt), so there is no liability and no warranty. In light of that I don't know what you mean by "supported". The library is over 10 years old and well tested, being used on a continual basis for data recording of several scientific projects. The last release was to fix a typo, so hopefully all the major bugs were shaken out a long time ago.

The easiest way to find the available functions is to read the [class header file](https://github.com/stevemarple/MCP342x/blob/master/src/MCP342x.h). The library already contains some examples on how to use it, and follows the Arduino standard of including them in the [`examples`](https://github.com/stevemarple/MCP342x/tree/master/examples) directory. If you install the library in the Arduino IDE the examples will be presented to you from the `File | Examples` menu options.

I haven't created a _Read The Docs_ page for this library although I have done for some other Arduino libraries such as [AsyncDelay](https://asyncdelay.readthedocs.io/en/latest/); maybe one day I will add it. Feel free to create a pull-request - just [follow what I did](https://github.com/stevemarple/AsyncDelay/commit/d2a9d731bf6f846e41abbc34e01e4aa76db794f3) for AsyncDelay.

As the [README](https://github.com/stevemarple/MCP342x/blob/master/README.md) states:

> For the low level I2C protocol this library depends on the Arduino Wire library.

`Wire.h` is part of the standard Arduino Wire library.
